import {z} from 'zod';
import {db,user,siteOwner,originOK} from '@/lib/server';
import {emptyPicks,type Tournament,type Picks} from '@/lib/game';
const initial: Tournament={id:'match-picks',name:'Match picks',example:false,phase:'seeding',seedLock:'2099-01-01T00:00:00Z',fantasyLock:'2099-01-01T00:00:00Z',bracketLock:'2099-01-02T00:00:00Z',teams:[],players:[],qualified:[],results:{},matches:[]};
async function read(){const row=await db().prepare('SELECT data FROM tournaments WHERE id = ?').bind('active').first<{data:string}>();const t=row?JSON.parse(row.data) as Tournament:structuredClone(initial);t.players||=[];return {raw:row?.data,t};}
const action=z.discriminatedUnion('action',[
 z.object({action:z.literal('team'),name:z.string().trim().min(1).max(50)}),
 z.object({action:z.literal('editTeam'),id:z.string().min(1),name:z.string().trim().min(1).max(50),color:z.string().regex(/^#[0-9a-fA-F]{6}$/)}),
 z.object({action:z.literal('player'),name:z.string().trim().min(1).max(50),team:z.string(),discordId:z.string().regex(/^\d{15,22}$/)}),
 z.object({action:z.literal('match'),a:z.string(),b:z.string(),lock:z.string().datetime()}),
 z.object({action:z.literal('result'),id:z.string(),winner:z.string()}),
 z.object({action:z.literal('pick'),id:z.string(),winner:z.string()})
]);
export async function GET(r:Request){try{const owner=await siteOwner(r);const u=await user(r)||owner;const {t}=await read();const row=u?await db().prepare('SELECT data FROM entries WHERE user = ? AND tournament = ?').bind(u.id,t.id).first<{data:string}>():null;const p:Picks=row?JSON.parse(row.data):emptyPicks();return Response.json({teams:t.teams,matches:t.matches,picks:p.matches,user:u,owner:!!owner,points:t.matches.reduce((n,m)=>n+(m.winner&&p.matches[m.id]===m.winner?100:0),0)},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Could not load matches. Please try again.'},{status:503});}}
export async function POST(r:Request){try{if(!originOK(r))return Response.json({error:'Forbidden'},{status:403});const owner=await siteOwner(r);const u=await user(r)||owner;if(!u)return Response.json({error:'Sign in to continue.'},{status:401});const rawBody=await r.text();if(rawBody.length>4000)throw Error('Request too large.');const a=action.parse(JSON.parse(rawBody));const {t,raw}=await read();if(a.action==='pick'){if(!await user(r))return Response.json({error:'Sign in with Discord to save picks.'},{status:401});const m=t.matches.find(m=>m.id===a.id);if(!m||![m.a,m.b].includes(a.winner))throw Error('Choose one of the teams in this match.');const memberTeam=t.players.find(player=>player.discordId===u.id)?.team;if(memberTeam&&[m.a,m.b].includes(memberTeam))throw Error('You cannot pick a match involving your own team.');if(m.winner||Date.now()>=Date.parse(m.lock))throw Error('Picks are locked for this match.');const row=await db().prepare('SELECT data FROM entries WHERE user = ? AND tournament = ?').bind(u.id,t.id).first<{data:string}>();const p:Picks=row?JSON.parse(row.data):emptyPicks();p.matches[a.id]=a.winner;const result=row?await db().prepare('UPDATE entries SET data = ? WHERE user = ? AND tournament = ? AND data = ? AND EXISTS (SELECT 1 FROM tournaments WHERE id = ? AND data = ?)').bind(JSON.stringify(p),u.id,t.id,row.data,'active',raw).run():await db().prepare('INSERT INTO entries (user,tournament,data) SELECT ?,?,? WHERE EXISTS (SELECT 1 FROM tournaments WHERE id = ? AND data = ?) ON CONFLICT(user,tournament) DO NOTHING').bind(u.id,t.id,JSON.stringify(p),'active',raw).run();if(!result.meta.changes)return Response.json({error:'The match changed. Refresh and try again.'},{status:409});return Response.json({saved:true});}
 if(!owner)return Response.json({error:'Only the site owner can manage teams and results.'},{status:403});
 if(a.action==='editTeam'){const team=t.teams.find(x=>x.id===a.id);if(!team)throw Error('Team not found.');if(t.teams.some(x=>x.id!==a.id&&x.name.toLowerCase()===a.name.toLowerCase()))throw Error('That team name already exists.');team.name=a.name;team.short=a.name.slice(0,3).toUpperCase();team.color=a.color;}
 if(a.action==='team'){if(t.teams.length>=64)throw Error('Team limit reached.');if(t.teams.some(x=>x.name.toLowerCase()===a.name.toLowerCase()))throw Error('That team already exists.');t.teams.push({id:crypto.randomUUID(),name:a.name,short:a.name.slice(0,3).toUpperCase(),color:['#bef264','#a78bfa','#38bdf8','#fb923c'][t.teams.length%4]});}
 if(a.action==='player'){if(!t.teams.some(x=>x.id===a.team))throw Error('Choose a valid team.');if(t.players.length>=256)throw Error('Player limit reached.');if(t.players.some(x=>x.discordId===a.discordId))throw Error('That Discord account is already assigned to a team.');t.players.push({id:crypto.randomUUID(),name:a.name,team:a.team,discordId:a.discordId,points:0});}
 if(a.action==='match'){if(t.matches.length>=200)throw Error('Match limit reached.');if(a.a===a.b||![a.a,a.b].every(id=>t.teams.some(x=>x.id===id)))throw Error('Choose two different teams.');if(Date.parse(a.lock)<=Date.now())throw Error('Choose a future start time.');t.matches.push({id:crypto.randomUUID(),a:a.a,b:a.b,lock:a.lock,week:t.currentWeek||'Week 1',stage:t.phase==='bracket'?'bracket':'seeding',betsOpen:true});}
 if(a.action==='result'){const m=t.matches.find(x=>x.id===a.id);if(!m||![m.a,m.b].includes(a.winner))throw Error('Invalid winner.');if(Date.now()<Date.parse(m.lock))throw Error('Results can be recorded after the match starts.');m.winner=a.winner;}
 const result=raw?await db().prepare('UPDATE tournaments SET data = ? WHERE id = ? AND data = ?').bind(JSON.stringify(t),'active',raw).run():await db().prepare('INSERT INTO tournaments (id,data) VALUES (?,?) ON CONFLICT(id) DO NOTHING').bind('active',JSON.stringify(t)).run();if(!result.meta.changes)return Response.json({error:'Someone updated the matches. Refresh and try again.'},{status:409});return Response.json({saved:true});}catch(e){return Response.json({error:e instanceof z.ZodError?'Check the team names and match details.':e instanceof Error?e.message:'Could not save. Try again.'},{status:400});}}
