'use client';
import {useEffect,useState} from 'react';
import Organizer from './organizer';
import {ArrowUpRight, Check, ChevronRight, Crosshair, GitBranch, LockKeyhole, Trophy, Users, Zap, Shield, LogOut} from 'lucide-react';
import {example,emptyPicks,pairings,type Picks,type Tournament} from '@/lib/game';
type Mode='matches'|'fantasy'|'bracket';
export default function Home(){
 const [mode,setMode]=useState<Mode>('matches');const [t,setT]=useState<Tournament>(example);const [p,setP]=useState<Picks>(emptyPicks());const [user,setUser]=useState<{id:string;name:string}|null>(null);const [notice,setNotice]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [points,setPoints]=useState(0);const [admin,setAdmin]=useState(false);const [organizer,setOrganizer]=useState(false);const [stage,setStage]=useState<'seeding'|'bracket'>('seeding');
 async function load(){try{const r=await fetch('/api/game');if(!r.ok)throw Error();const d=await r.json() as {user:{id:string;name:string}|null;tournament:Tournament;picks:Picks;score:number;admin:boolean;unavailable?:boolean};setUser(d.user);setT(d.tournament);setP(d.picks);setPoints(d.score);setAdmin(d.admin);setStage(d.tournament.phase==='seeding'?'seeding':'bracket');if(d.unavailable)setNotice('Tournament service is being connected. You can preview the example below.');}catch{setNotice('Could not load your picks. Refresh to try again.');}finally{setLoading(false);}}
 useEffect(()=>{void load();const auth=new URLSearchParams(location.search).get('auth');if(auth)setNotice(auth==='setup'?'Discord sign-in needs to be connected by the site owner.':'Discord sign-in did not finish. Please try again.');},[]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'open_prediction_mode',description:'Open match picks, fantasy rosters, or tournament bracket picks. Does not submit entries.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['matches','fantasy','bracket']}},required:['mode'],additionalProperties:false},execute(input:{mode:Mode}){if(!['matches','fantasy','bracket'].includes(input.mode))throw Error('Unknown mode');setMode(input.mode);return {opened:input.mode};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const team=(id:string)=>t.teams.find(x=>x.id===id);
 const canPlay=!!user&&!t.example&&!loading;
 const isLocked=(date:string)=>Date.now()>=Date.parse(date);
 function change(next:Picks){if(!user){setNotice('Sign in with Discord to make your picks.');return;}if(t.example){setNotice('These are example teams. Entries open when an organizer publishes a tournament.');return;}setP(next);setNotice('Unsaved changes. Save your picks when you’re ready.');}
 async function save(){setBusy(true);try{const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tournament:t.id,picks:p})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setNotice('Your picks are saved. You can edit them until they lock.');}catch(e){setNotice(e instanceof Error?e.message:'Could not save. Your picks are still here.');}finally{setBusy(false);}}
 function toggle(kind:'fantasy'|'seeding',id:string){const list=p[kind];if(!list.includes(id)&&list.length===4){setNotice('Remove a pick before choosing another.');return;}change({...p,[kind]:list.includes(id)?list.filter(x=>x!==id):[...list,id]});}
 const badge=(id:string,size='')=>{const x=team(id);return <span className={'team-badge '+size} style={{'--team-color':x?.color||'#64748b'} as React.CSSProperties}>{x?.short.slice(0,1)||'?'}</span>;};
 return <div className="site-shell"><aside className="sidebar"><a href="/" className="brand"><span className="brand-mark">G</span><span>GORILLA<span className="brand-bottom">FANTASY</span></span></a><div className="nav-label">THE PLAYBOOK</div><nav aria-label="Main navigation">{([{id:'matches',label:'Match picks',Icon:Crosshair},{id:'fantasy',label:'Fantasy roster',Icon:Users},{id:'bracket',label:'Bracket predictions',Icon:GitBranch}] as const).map(({id,label,Icon})=><button key={id} className={mode===id?'nav-item active':'nav-item'} onClick={()=>setMode(id)} aria-current={mode===id?'page':undefined}><Icon size={19}/>{label}{mode===id&&<ChevronRight size={15}/>}</button>)}</nav><div className="sidebar-note"><Shield size={22}/><strong>Knowledge wins.</strong><p>Make your reads.<br/>Back your team.<br/>Climb on match day.</p><span>FREE TO PLAY · NO CASH VALUE</span></div><div className="sidebar-bottom"><span className="mini-dot"/> Competitive Gorilla Tag</div></aside>
 <div className="main-shell"><header className="topbar"><span className="breadcrumb">Play / <strong>{mode==='matches'?'Match picks':mode==='fantasy'?'Fantasy roster':'Bracket predictions'}</strong></span><div className="account"><span className="points"><Zap size={16}/>{points} <span>PTS</span></span>{user?<><span className="username">{user.name}</span><button className="icon-button" title="Sign out" onClick={async()=>{const r=await fetch('/api/auth/logout',{method:'POST'});if(r.ok)location.reload();else setNotice('Could not sign out. Try again.');}}><LogOut size={18}/></button></>:<a className="discord-button" href="/api/auth/login">Sign in with Discord <ArrowUpRight size={16}/></a>}</div></header>
 <main><div className="page-heading"><div><div className="eyebrow">COMPETITIVE GORILLA TAG</div><h1>{mode==='matches'?'Make your call.':mode==='fantasy'?'Build your four.':'Call the whole run.'}</h1><p>{mode==='matches'?'Two teams. Five rounds. Who takes the win?':mode==='fantasy'?'Pick four players. Their tournament performance earns your points.':'From the qualifying spots to the final. Put your tournament knowledge to work.'}</p></div><span className="season-pill"><Trophy size={16}/> {t.name}</span></div>
 <section className="tournament-strip"><div><span className="event-label">{t.example?'EXAMPLE TOURNAMENT':'CURRENT TOURNAMENT'}</span><strong>{t.name}</strong></div><div className="event-stat"><span>FORMAT</span><strong>4v4 · Best of 5</strong></div><div className="event-stat"><span>TEAMS</span><strong>{t.teams.length} contenders</strong></div><div className="event-stat"><span>STAGE</span><strong>{t.phase==='seeding'?'Seeding':t.phase==='bracket'?'Bracket':'Completed'}</strong></div><span className="event-icon"><GitBranch size={32}/></span></section>
 {!user&&<div className="signin-banner"><LockKeyhole size={21}/><div><strong>Your picks start with Discord.</strong><span>Sign in to save your roster and predictions.</span></div><a href="/api/auth/login">Connect Discord <ArrowUpRight size={16}/></a></div>}
 {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss message">×</button></div>}
 {t.example&&<p className="example-note">Preview only · Teams and schedules below are examples. No live competition is connected yet.</p>}
 <div className="workspace"><section className="primary-area">
 {mode==='matches'&&<><div className="section-heading"><h2>Match winners <span>{t.matches.length}</span></h2><span>100 pts per correct pick</span></div><div className="match-list">{t.matches.map((m,i)=><article className="match-card" key={m.id}><div className="match-meta"><span>MATCH {String(i+1).padStart(2,'0')} <b>BO5</b></span><span>{m.winner?'FINAL':isLocked(m.lock)?'PICKS LOCKED':new Date(m.lock).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</span></div><div className="match-teams"><div>{badge(m.a)}<strong>{team(m.a)?.name}</strong></div><span className="versus">VS</span><div>{badge(m.b)}<strong>{team(m.b)?.name}</strong></div></div><div className="pick-buttons">{[m.a,m.b].map(id=><button key={id} disabled={!canPlay||isLocked(m.lock)||!!m.winner||busy} className={p.matches[m.id]===id?'selected':''} onClick={()=>change({...p,matches:{...p.matches,[m.id]:id}})}>{p.matches[m.id]===id?<Check size={16}/>:<span className="radio-circle"/>}{team(id)?.name} to win</button>)}</div>{m.winner&&<p className="result">Winner: {team(m.winner)?.name}</p>}</article>)}</div></>}
 {mode==='fantasy'&&<><div className="section-heading"><h2>Player pool</h2><span>{p.fantasy.length} / 4 selected</span></div><div className="roster-slots">{[0,1,2,3].map(i=><div key={i} className={p.fantasy[i]?'filled':''}><span>{String(i+1).padStart(2,'0')}</span><strong>{t.players.find(x=>x.id===p.fantasy[i])?.name||'Open slot'}</strong></div>)}</div><div className="players">{t.players.map(x=><button key={x.id} className={'player-row '+(p.fantasy.includes(x.id)?'selected':'')} disabled={!canPlay||isLocked(t.fantasyLock)||busy} onClick={()=>toggle('fantasy',x.id)}>{badge(x.team,'small')}<span><strong>{x.name}</strong><small>{team(x.team)?.name}</small></span><span className="player-score">{x.points} pts</span><span className="pick-check">{p.fantasy.includes(x.id)?<Check size={17}/>:'+'}</span></button>)}</div></>}
 {mode==='bracket'&&<><div className="stage-tabs"><button className={stage==='seeding'?'active':''} onClick={()=>setStage('seeding')}><span>01</span> Qualifiers</button><ChevronRight size={18}/><button className={stage==='bracket'?'active':''} onClick={()=>setStage('bracket')}><span>02</span> Bracket & finals</button></div>{stage==='seeding'?<><div className="section-heading"><h2>Who makes the cut?</h2><span>{p.seeding.length} / 4 teams</span></div><p className="section-description">Choose the four teams you think will qualify. Picks lock before seeding begins.</p><div className="qualifier-grid">{t.teams.map(x=><button key={x.id} disabled={!canPlay||t.phase!=='seeding'||isLocked(t.seedLock)||busy} className={'qualifier '+(p.seeding.includes(x.id)?'selected':'')} onClick={()=>toggle('seeding',x.id)}>{badge(x.id)}<strong>{x.name}</strong><span className="pick-check">{p.seeding.includes(x.id)?<Check size={17}/>:'+'}</span></button>)}</div></>:t.qualified.length!==4?<div className="bracket-wait"><GitBranch size={48}/><h2>The bracket starts after seeding.</h2><p>Once the four qualifying teams are confirmed, pick both semifinal winners and your finals champion.</p><div className="ghost-bracket"><span>Seed 1 vs Seed 4</span><span>Seed 2 vs Seed 3</span><strong><Trophy size={20}/> Your champion</strong></div></div>:<><div className="section-heading"><h2>Pick your path to the trophy</h2></div><div className="bracket-grid">{pairings(t.qualified,p.bracket).map(match=><article key={match.id} className={'bracket-match '+(match.id==='final'?'final-match':'')}><span>{match.id==='final'?'FINALS CHAMPION':match.id==='s1'?'SEMIFINAL 1':'SEMIFINAL 2'}</span>{match.teams.map((id,i)=><button key={i} disabled={!id||!canPlay||t.phase!=='bracket'||isLocked(t.bracketLock)||busy} className={p.bracket[match.id]===id&&id?'selected':''} onClick={()=>{const b={...p.bracket,[match.id]:id};if(match.id!=='final'&&p.bracket[match.id]!==id)delete b.final;change({...p,bracket:b});}}>{badge(id)}{team(id)?.name||'Pick a semifinal winner'}{id&&p.bracket[match.id]===id&&<Check size={17}/>}</button>)}</article>)}</div></>}</>}
 </section><aside className="right-rail"><section className="entry-panel"><div className="panel-icon"><Trophy size={23}/></div><h2>Your playbook</h2><p>One account. Every way to play.</p><div className="entry-line"><span>Match picks</span><strong>{Object.keys(p.matches).length} / {t.matches.length}</strong></div><div className="entry-line"><span>Fantasy roster</span><strong>{p.fantasy.length} / 4</strong></div><div className="entry-line"><span>Qualifying teams</span><strong>{p.seeding.length} / 4</strong></div><div className="entry-line"><span>Bracket picks</span><strong>{Object.keys(p.bracket).length} / 3</strong></div><button className="save-button" disabled={!canPlay||busy} onClick={save}>{busy?'Saving…':user?'Save my picks':'Sign in to play'}<ArrowUpRight size={17}/></button><small>{user?'You can edit until each phase locks.':'Discord sign-in required to enter.'}</small></section><section className="rules-panel"><h3><Crosshair size={17}/> How the match works</h3><ol><li>Both teams take a timed run each round.</li><li>The longer team run wins the round.</li><li>First to three round wins takes the match.</li></ol><p>Play for points. No deposits, cash bets, or payouts.</p></section>{mode==='fantasy'&&<section className="rules-panel"><h3>Fantasy scoring</h3><p>1 point per completed second of individual survival, plus 5 per confirmed tag. Organizers enter verified totals.</p></section>}{mode==='bracket'&&<section className="rules-panel"><h3>Prediction points</h3><p>25 per correct qualifier · 50 per semifinal winner · 100 for the champion.</p><p>Qualifier lock: {new Date(t.seedLock).toLocaleString()}<br/>Bracket lock: {new Date(t.bracketLock).toLocaleString()}</p></section>}</aside></div>
 {admin&&<section className="admin-panel"><button onClick={()=>setOrganizer(!organizer)}>Organizer controls</button>{organizer&&<Organizer tournament={t} onSaved={load}/>}</section>}
 <footer><span>GORILLA FANTASY <span> / </span> Read the game.</span><span>Community project · Not affiliated with Another Axiom</span></footer></main></div></div>;
}


