import type {Match,Picks,Tournament} from './game';
export const STARTING_POINTS=100;
export function normalizeTournament(t:Tournament):Tournament{return {...t,currentWeek:t.currentWeek||'Week 1',matches:t.matches.map(m=>({...m,week:m.week||t.currentWeek||'Week 1',stage:m.stage||(t.phase==='bracket'?'bracket':'seeding'),betsOpen:m.betsOpen??true}))};}
export function normalizePicks(p:Picks):Picks{return {...emptyShape(),...p,singleBets:p.singleBets||{},weekBets:p.weekBets||{}};}
function emptyShape():Picks{return {fantasy:[],seeding:[],bracket:{},matches:{},singleBets:{},weekBets:{}};}
export function wallet(p:Picks,t:Tournament){const n=normalizePicks(p);let total=STARTING_POINTS;for(const [id,b] of Object.entries(n.singleBets!)){total-=b.stake;const m=t.matches.find(x=>x.id===id);if(m?.winner===b.winner)total+=b.stake*2;}for(const [key,b] of Object.entries(n.weekBets!)){total-=b.stake;const [stage,...weekParts]=key.split(':');const games=weekMatches(t,weekParts.join(':'),stage as 'seeding'|'bracket');if(games.length&&games.every(m=>m.winner)&&games.every(m=>b.picks[m.id]===m.winner))total+=b.stake*3;}return total;}
export function weekKey(stage:string,week:string){return `${stage}:${week}`;}
export function weekMatches(t:Tournament,week:string,stage=t.phase){return t.matches.filter(m=>(m.week||'Week 1')===week&&(m.stage||'seeding')===stage);}
export function canBet(m:Match,now=Date.now()){return m.betsOpen!==false&&!m.winner&&now<Date.parse(m.lock);}
export function placeSingle(p:Picks,t:Tournament,id:string,winner:string,stake:number,now=Date.now()){const n=normalizePicks(p);const m=t.matches.find(x=>x.id===id);if(!m||![m.a,m.b].includes(winner))throw Error('Choose one of the teams in this match.');if(!canBet(m,now))throw Error('Betting is closed for this match.');if(n.singleBets![id])throw Error('You already placed a bet on this match.');if(n.weekBets![weekKey(m.stage||'seeding',m.week||'Week 1')])throw Error('You already placed a full-week bet for this week.');if(!Number.isInteger(stake)||stake<1||stake>wallet(n,t))throw Error('Choose a whole-number stake within your available balance.');n.singleBets![id]={winner,stake,placedAt:new Date(now).toISOString()};return n;}
export function placeWeek(p:Picks,t:Tournament,week:string,stage:'seeding'|'bracket',picks:Record<string,string>,stake:number,now=Date.now()){const n=normalizePicks(p);const games=weekMatches(t,week,stage);const key=weekKey(stage,week);if(!games.length)throw Error('There are no matches in this week.');if(n.weekBets![key])throw Error('You already placed a full-week bet for this week.');if(games.some(m=>n.singleBets![m.id]))throw Error('You already placed a single-match bet this week.');if(games.some(m=>!canBet(m,now)))throw Error('The full-week bet is closed because a match started or was closed.');if(Object.keys(picks).length!==games.length||games.some(m=>![m.a,m.b].includes(picks[m.id])))throw Error('Pick a winner for every match this week.');if(!Number.isInteger(stake)||stake<1||stake>wallet(n,t))throw Error('Choose a whole-number stake within your available balance.');n.weekBets![key]={picks:{...picks},stake,placedAt:new Date(now).toISOString()};return n;}
