import {z} from 'zod';
import {cancelSingle} from '@/lib/bets';
import {matchVotes} from '@/lib/votes';
import {db,user,siteOwner,originOK} from '@/lib/server';
import {emptyPicks,type Picks,type Tournament} from '@/lib/game';
import {normalizePicks,normalizeTournament,placeSingle,placeWeek,wallet} from '@/lib/bets';
const initial:Tournament={id:'match-picks',name:'Match picks',example:false,phase:'seeding',currentWeek:'Week 1',seedLock:'2099-01-01T00:00:00Z',fantasyLock:'2099-01-01T00:00:00Z',bracketLock:'2099-01-02T00:00:00Z',teams:[],players:[],qualified:[],results:{},matches:[]};
const action=z.discriminatedUnion('action',[
 z.object({action:z.literal('cancel'),id:z.string().min(1)}),
 z.object({action:z.literal('settings'),phase:z.enum(['seeding','bracket']),week:z.string().trim().min(1).max(40)}),
 z.object({action:z.literal('betState'),id:z.string(),open:z.boolean()}),
 z.object({action:z.literal('single'),id:z.string(),winner:z.string(),stake:z.number().int().min(1)}),
 z.object({action:z.literal('week'),week:z.string(),stage:z.enum(['seeding','bracket']),picks:z.record(z.string(),z.string()),stake:z.number().int().min(1)})
]);
async function current(){const row=await db().prepare('SELECT data FROM tournaments WHERE id = ?').bind('active').first<{data:string}>();return {raw:row?.data,t:normalizeTournament(row?JSON.parse(row.data) as Tournament:structuredClone(initial))};}
export async function GET(r:Request){try{const owner=await siteOwner(r);const discord=await user(r);if(discord)await db().prepare('INSERT INTO entries (user,tournament,data) VALUES (?,?,?) ON CONFLICT(user,tournament) DO UPDATE SET data=excluded.data').bind(discord.id,'profile',JSON.stringify({name:discord.name})).run();const u=discord||owner;const {t}=await current();const row=u?await db().prepare('SELECT data FROM entries WHERE user = ? AND tournament = ?').bind(u.id,t.id).first<{data:string}>():null;const p=normalizePicks(row?JSON.parse(row.data):emptyPicks());const all=u?await db().prepare('SELECT data FROM entries WHERE tournament = ?').bind(t.id).all<{data:string}>():{results:[]};const votes=matchVotes(t.matches,all.results.map(row=>JSON.parse(row.data) as Picks));const memberTeam=discord?t.players.find(player=>player.discordId===discord.id)?.team:null;const publicPlayers=t.players.map(({discordId:_,...player})=>player);return Response.json({votes,teams:t.teams,players:publicPlayers,matches:discord||owner?t.matches:[],phase:t.phase==='bracket'?'bracket':'seeding',currentWeek:t.currentWeek||'Week 1',memberTeam,bets:{single:p.singleBets,weekly:p.weekBets},points:wallet(p,t),user:u,owner:!!owner,discordAuthenticated:!!discord},{headers:{'Cache-Control':'no-store'}});}catch(e){return Response.json({error:e instanceof Error?e.message:'Could not load betting.'},{status:503});}}
export async function POST(r:Request){try{if(!originOK(r))return Response.json({error:'Forbidden'},{status:403});const owner=await siteOwner(r);const u=await user(r)||owner;if(!u)return Response.json({error:'Sign in to bet points.'},{status:401});const rawBody=await r.text();if(rawBody.length>12000)throw Error('Request too large.');const a=action.parse(JSON.parse(rawBody));const {t,raw}=await current();
 if(a.action==='week')throw Error('Full-week betting is no longer available.');
 if(a.action==='cancel'){if(!await user(r))return Response.json({error:'Sign in with Discord to cancel your bet.'},{status:401});const row=await db().prepare('SELECT data FROM entries WHERE user = ? AND tournament = ?').bind(u.id,t.id).first<{data:string}>();if(!row)throw Error('There is no bet to cancel.');const next=cancelSingle(JSON.parse(row.data),t,a.id);const m=t.matches.find(m=>m.id===a.id)!;const result=await db().prepare("UPDATE entries SET data = ? WHERE user = ? AND tournament = ? AND data = ? AND EXISTS (SELECT 1 FROM tournaments WHERE id = ? AND data = ?) AND julianday(?) > julianday('now')").bind(JSON.stringify(next),u.id,t.id,row.data,'active',raw,m.lock).run();if(!result.meta.changes)throw Error('The match or your bet changed. Refresh and try again.');return Response.json({saved:true});}
 if(a.action==='single'){if(!await user(r))return Response.json({error:'Sign in with Discord to place bets.'},{status:401});const row=await db().prepare('SELECT data FROM entries WHERE user = ? AND tournament = ?').bind(u.id,t.id).first<{data:string}>();const old=normalizePicks(row?JSON.parse(row.data):emptyPicks());const memberTeam=t.players.find(player=>player.discordId===u.id)?.team;const next=placeSingle(old,t,a.id,a.winner,a.stake,Date.now(),memberTeam);const write=row?db().prepare('UPDATE entries SET data = ? WHERE user = ? AND tournament = ? AND data = ? AND EXISTS (SELECT 1 FROM tournaments WHERE id = ? AND data = ?)').bind(JSON.stringify(next),u.id,t.id,row.data,'active',raw):db().prepare('INSERT INTO entries (user,tournament,data) SELECT ?,?,? WHERE EXISTS (SELECT 1 FROM tournaments WHERE id = ? AND data = ?) ON CONFLICT(user,tournament) DO NOTHING').bind(u.id,t.id,JSON.stringify(next),'active',raw);const [result]=await db().batch([write,db().prepare("DELETE FROM entries WHERE user = ? AND tournament = 'leaderboard:hidden' AND changes() > 0").bind(u.id)]);if(!result.meta.changes)throw Error('The match or your balance changed. Refresh and try again.');return Response.json({saved:true});}
 if(!owner)return Response.json({error:'Only the owner can change the stage or betting status.'},{status:403});
 if(a.action==='settings'){t.phase=a.phase;t.currentWeek=a.week;}
 if(a.action==='betState'){const m=t.matches.find(x=>x.id===a.id);if(!m)throw Error('Match not found.');if(a.open&&(m.winner||Date.now()>=Date.parse(m.lock)))throw Error('A started or completed match cannot reopen.');m.betsOpen=a.open;}
 const changed=raw?await db().prepare('UPDATE tournaments SET data = ? WHERE id = ? AND data = ?').bind(JSON.stringify(t),'active',raw).run():await db().prepare('INSERT INTO tournaments (id,data) VALUES (?,?) ON CONFLICT(id) DO NOTHING').bind('active',JSON.stringify(t)).run();if(!changed.meta.changes)throw Error('The schedule changed. Refresh and try again.');return Response.json({saved:true});
 }catch(e){return Response.json({error:e instanceof z.ZodError?'Check your selections and point amount.':e instanceof Error?e.message:'Could not save.'},{status:400});}}
